# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VIKING GARAGE
email: ride@vikinggarage.com
description: > # this means to ignore newlines until "baseurl:"
  VIKING GARAGE oferuje wynajem motocykli na terenie Warszawy i okolic. Dostępne typy:
  motocross, enduro, custom, na prawo jazdy kat. B lub na torach i w terenie przełajowym.
  Możliwości: sprzęt ochronny, transport, instruktorzy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vikinggarage.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  michalmikolajczyk

# Build settings
markdown: kramdown
theme: cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
